app/routes.php
<?php

/*
  |--------------------------------------------------------------------------
  | Application Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register all of the routes for an application.
  | It's a breeze. Simply tell Laravel the URIs it should respond to
  | and give it the Closure to execute when that URI is requested.
  |
 */

//Route::get('/', function()
//{
//	return View::make('hello');
//});

Route::get('/', 'HomeController@showLogin');

Route::get('about', function() {
    return View::make('about');
});

Route::get('contact', 'PagesController@contact');

Route::resource('users', 'UsersController');
Route::resource('album', 'AlbumController@index');
Route::resource('posts', 'PostsController');

//Route::resource('signin', 'UsersController@signin');
/* Route::resource('login', 'UsersController@login'); */


Route::get('login', array('uses' => 'HomeController@showLogin'));
Route::get('logout', 'HomeController@destroy');

Route::post('login', array('uses' => 'HomeController@doLogin'));

Route::get('admin', function() {
  return View::make('album_create');
});

Route::resource('album_create', 'AlbumController');





//Route::get('logout', array('as' => 'logout', function () {
//    Auth::logout();
//     return View::make('album_create');
//
//    return Redirect::route('login')
//        ->with('flash_notice', 'You are successfully logged out.');
//}))->before('auth');

app/models/User.php
<?php
use Illuminate\Auth\UserInterface;
use Illuminate\Auth\Reminders\RemindableInterface;
use Spekkionu\ZendAcl\Facades\Acl;


class User extends Eloquent implements UserInterface, RemindableInterface  {

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';
 
    protected $fillable = array('username', 'password', 'email','phone','name');
//	 protected $fillable = array('email','password');
	//protected $fillable = ['parent', 'title'];
	 
        public static $rules = array(
		'name' => 'required|min:5',
		'email' => 'required|email'
	);


	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array('password');

	/**
	 * Get the unique identifier for the user.
	 *
	 * @return mixed
	 */
	public function getAuthIdentifier()
	{
		return $this->getKey();
	}

	/**
	 * Get the password for the user.
	 *
	 * @return string
	 */
	public function getAuthPassword()
	{
		return $this->password;
	}

	/**
	 * Get the e-mail address where password reminders are sent.
	 *
	 * @return string
	 */
	public function getReminderEmail()
	{
		return $this->email;
	}
        public function getRememberToken()
       {
           return $this->remember_token;   
       }

       public function setRememberToken($value)
       {
           $this->remember_token = $value;
       } 

       public function getRememberTokenName()
       {
           return 'remember_token';
       } 
        public function getRoleId()
    {
        return $this->role;
    }
}

app/controllers/UsersController.php
<?php

class UsersController extends BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
          
            
 	$users = User::paginate(5);
        return View::make('users.index', compact('users'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
	return View::make('users.create'); 
		
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
	$input = Input::all();
	$validation = Validator::make($input, User::$rules);

        if ($validation->passes())
        { 
	 /* User::create($input);*/
	$user = new User;
        $user->username = Input::get('username');
	$user->password = Hash::make(Input::get('password'));
        $user->email = Input::get('email');
	$user->phone = Input::get('phone');
	$user->name = Input::get('name');
        if($user->save())
            {
                    return Redirect::route('users.index');
            }
	}

        return Redirect::route('users.create')
            ->withInput()
            ->withErrors($validation)
            ->with('message', 'There were validation errors.');

	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$user = User::find($id);
        if (is_null($user))
        {
            return Redirect::route('users.index');
        }
        return View::make('users.edit', compact('user'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
	$input = Input::all();
        $validation = Validator::make($input, User::$rules);
		
        if ($validation->passes())
        {	 
		 
            $user = User::find($id);
            $user->update($input);
            return Redirect::route('users.index');
        }
		return Redirect::route('users.edit', $id)
            ->withInput()
            ->withErrors($validation)
            ->with('message', 'There were validation errors.');

	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
	User::find($id)->delete();
        return Redirect::route('users.index');
	}
  
       
	
/*	public function login() {
	 
	 return View::make("users.login");
}*/

/*public function signin() {
	  
	 		$userdata = array(
				'email' 	=> Input::get('email'),
				'password' => Input::get('password')
			);
			 dd($userdata);
	 if (Auth::attempt($userdata)) {
    die('logeed inn');
} else {
    return Redirect::to('login')
        ->with('message', 'Your username/password combination was incorrect')
        ->withInput();
}
} */


}

app/views/users/create.blade.php
@extends('layouts.user')

@section('main')

<h1>Create User</h1>

{{ Form::open(array('route' => 'users.store')) }}
    <ul>

        <li>
            {{ Form::label('name', 'Name:') }}
            {{ Form::text('name') }}
        </li>

        <li>
            {{ Form::label('username', 'Username:') }}
            {{ Form::text('username') }}
        </li>

        <li>
            {{ Form::label('password', 'Password:') }}
            {{ Form::password('password') }}
        </li>

        <li>
            {{ Form::label('password', 'Confirm Password:') }}
            {{ Form::password('password_confirmation') }}
        </li>

        <li>
            {{ Form::label('email', 'Email:') }}
            {{ Form::text('email') }}
        </li>

        <li>
            {{ Form::label('phone', 'Phone:') }}
            {{ Form::text('phone') }}
        </li>


        <li>
            {{ Form::submit('Submit', array('class' => 'btn')) }}
        </li>
    </ul>
{{ Form::close() }}

@if ($errors->any())
    <ul>
        {{ implode('', $errors->all('<li class="error">:message</li>')) }}
    </ul>
@endif

@stop

app/views/users/edit.blade.php
@extends('layouts.user')

@section('main')

<h1>Edit User</h1>
{{ Form::model($user, array('method' => 'PATCH', 'route' => array('users.update', $user->id))) }}
    <ul>
        <li>
            {{ Form::label('username', 'Username:') }}
            {{ Form::text('username') }}
        </li>
        <li>
            {{ Form::label('password', 'Password:') }}
            {{ Form::text('password') }}
        </li>
        <li>
            {{ Form::label('email', 'Email:') }}
            {{ Form::text('email') }}
        </li>
        <li>
            {{ Form::label('phone', 'Phone:') }}
            {{ Form::text('phone') }}
        </li>
        <li>
            {{ Form::label('name', 'Name:') }}
            {{ Form::text('name') }}
        </li>
        <li>
            {{ Form::submit('Update', array('class' => 'btn btn-info')) }}
            {{ link_to_route('users.show', 'Cancel', $user->id, array('class' => 'btn')) }}
        </li>
    </ul>
{{ Form::close() }}

@if ($errors->any())
    <ul>
        {{ implode('', $errors->all('<li class="error">:message</li>')) }}
    </ul>
@endif

@stop

app/views/users/index.blade.php
@extends('layouts/user')

@section('main')

<h1>All Users</h1>

<p>{{ link_to_route('users.create', 'Add new user') }}</p>

@if ($users->count())
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Name</th>
            <th>Username</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Name</th>
        </tr>
    </thead>

    <tbody>
        @foreach ($users as $user)
        <tr>
            <td>{{ $user->name }}</td>	
            <td>{{ $user->username }}</td>
            <td>{{ $user->email }}</td>
            <td>{{ $user->phone }}</td>
            <td>{{ link_to_route('users.edit', 'Edit', array($user->id), array('class' => 'btn btn-info')) }}</td>
            <td>
                {{ Form::open(array('method'
=> 'DELETE', 'route' => array('users.destroy', $user->id))) }}
                {{ Form::submit('Delete', array('class' => 'btn btn-danger')) }}
                {{ Form::close() }}
            </td>
        </tr>
        @endforeach

    </tbody>

</table>
<div class="pagination">
    {{ $users->links() }}
</div>

@else
There are no users
@endif

@stop

app/views/users/login.blade.php
 
@extends('layouts.user')

@section('main')
 
{{ Form::open(array('url'=>'users/signin', 'class'=>'form-signin')) }}
    <h2 class="form-signin-heading">Please Login</h2>
 
    {{ Form::text('email', null, array('class'=>'input-block-level', 'placeholder'=>'Email Address')) }}
    {{ Form::password('password', array('class'=>'input-block-level', 'placeholder'=>'Password')) }}
 
    {{ Form::submit('Login', array('class'=>'btn btn-large btn-primary btn-block'))}}
{{ Form::close() }}

@if ($errors->any())
    <ul>
        {{ implode('', $errors->all('<li class="error">:message</li>')) }}
    </ul>
@endif

@stop 

app/views/users/login1.blade.php
 
@extends('layouts.user')

@section('main')

<h1>Login User</h1>

{{ Form::open(array('url'=>'users/signin', 'class'=>'form-signin')) }}
    <h2 class="form-signin-heading">Please Login</h2>
 
    {{ Form::text('email', null, array('class'=>'input-block-level', 'placeholder'=>'Email Address')) }}
    {{ Form::password('password', array('class'=>'input-block-level', 'placeholder'=>'Password')) }}
 
    {{ Form::submit('Login', array('class'=>'btn btn-large btn-primary btn-block'))}}
{{ Form::close() }}

@if ($errors->any())
    <ul>
        {{ implode('', $errors->all('<li class="error">:message</li>')) }}
    </ul>
@endif

@stop