app/routes.php
<?php

/*
  |--------------------------------------------------------------------------
  | Application Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register all of the routes for an application.
  | It's a breeze. Simply tell Laravel the URIs it should respond to
  | and give it the Closure to execute when that URI is requested.
  |
 */

//Route::get('/', function()
//{
//	return View::make('hello');
//});

Route::get('/', 'HomeController@showLogin');

Route::get('about', function() {
    return View::make('about');
});

Route::get('contact', 'PagesController@contact');

Route::resource('users', 'UsersController');
Route::resource('album', 'AlbumController@index');
Route::resource('posts', 'PostsController');

//Route::resource('signin', 'UsersController@signin');
/* Route::resource('login', 'UsersController@login'); */


Route::get('login', array('uses' => 'HomeController@showLogin'));
Route::get('logout', 'HomeController@destroy');

Route::post('login', array('uses' => 'HomeController@doLogin'));

Route::get('admin', function() {
  return View::make('album_create');
});

Route::resource('album_create', 'AlbumController');





//Route::get('logout', array('as' => 'logout', function () {
//    Auth::logout();
//     return View::make('album_create');
//
//    return Redirect::route('login')
//        ->with('flash_notice', 'You are successfully logged out.');
//}))->before('auth');

app/views/album.blade.php
@extends('layouts.album')
@section('main')
<!DOCTYPE html>
<html>
    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js" type="text/javascript"></script>
        {{ HTML::script('js/jquery.prettyPhoto.js') }}
        {{ HTML::style('css/prettyPhoto.css'); }} 
        <style type="text/css" media="screen">
            * { margin: 0; padding: 0; }



            h1 { font-family: Georgia; font-style: italic; margin-bottom: 10px; }

            h2 {
                font-family: Georgia;
                font-style: italic;
                margin: 25px 0 5px 0;
            }

            p { font-size: 1.2em; }

            ul li { display: inline; }

            .wide {
                border-bottom: 1px #000 solid;
                width: 4000px;
            }

            .fleft { float: left; margin: 0 20px 0 0; }

            .cboth { clear: both; }

            #main {
                background: #fff;
                margin: 0 auto;
                padding: 30px;
                width: 1000px;
            }
        </style>
    </head>
    <body>




        <div id="main">
            <ul class="gallery clearfix">
                @foreach ($results as $result)
                <li><a href="uploads/{{$result->image}}" rel="prettyPhoto[gallery1]"><img src="uploads/{{ $result->image}}" width="160" height="160" alt="{{ $result->title}}" /></a></li>
                @endforeach
            </ul> 


            @if ($errors->any())
            <ul>
                {{ implode('', $errors->all('<li class="error">:message</li>')) }}
            </ul>
            @endif
            @stop 

app/views/album_create.blade.php
@extends('layouts.user')
@section('main')
<h2 class="form-signin-heading">Create Album</h2>
<div class="wrap">
    <img id="uploadPreview" style="display:none;"/>
    {{ Form::open(array('action' => 'AlbumController@store','files'=>true,'style'=>'width:400px;')) }}
    <input id="uploadImage" type="file" accept="image/jpeg" name="image" />
    <input type="hidden" id="x" name="x" />
    <input type="hidden" id="y" name="y" />
    <input type="hidden" id="w" name="w" />
    <input type="hidden" id="h" name="h" />

    <br><br> 
    {{ Form::text('title', null, array('class'=>'input-block-level', 'placeholder'=>'Title')) }}
    {{ Form::text('tags', null,array('class'=>'input-block-level','id'=>'tags_1', 'placeholder'=>'tags')) }}
    {{ Form::submit('Post', array('class'=>'btn btn-large btn-primary btn-block'))}}
    {{ Form::close() }}
</div>
@if ($errors->any())
<ul>
    {{ implode('', $errors->all('<li class="error">:message</li>')) }}
</ul>
@endif
@stop 

app/views/login.blade.php
@extends('layouts.user')
@section('main')
<p style="font-size: 18px;">{{ link_to_route('users.create', 'Sign Up') }}</p>
<br>
{{ Form::open(array('url'=>'login', 'style'=>'width:400px;')) }}
<h2 class="form-signin-heading">Please Login</h2>

{{ Form::text('email', null, array('class'=>'input-block-level', 'placeholder'=>'Email Address')) }}
{{ Form::password('password', array('class'=>'input-block-level', 'placeholder'=>'Password')) }}

{{ Form::submit('Login', array('class'=>'btn btn-large btn-primary btn-block'))}}
{{ Form::close() }}



@if ($errors->any())
<ul>
    {{ implode('', $errors->all('<li class="error">:message</li>')) }}
</ul>
@endif

@stop

app/views/login2.blade.php
<!doctype html>
<html>
<head>
	<title>Look at me Login</title>
</head>
<body>

	{{ Form::open(array('url' => 'login')) }}
		<h1>Login</h1>

		<!-- if there are login errors, show them here -->
		@if (Session::get('loginError'))
		<div class="alert alert-danger">{{ Session::get('loginError') }}</div>
		@endif

		<p>
			{{ $errors->first('email') }}
			{{ $errors->first('password') }}
		</p>

		<p>
			{{ Form::label('email', 'Email Address') }}
			{{ Form::text('email', Input::old('email'), array('placeholder' => 'awesome@awesome.com')) }}
		</p>

		<p>
			{{ Form::label('password', 'Password') }}
			{{ Form::password('password') }}
		</p>

		<p>{{ Form::submit('Submit!') }}</p>
	{{ Form::close() }}

</body>
</html>